### ISSUE TITLE
How to output topk items to recommend from DSSM model

### ISSUE THREAD

**Issue by ss-github-code** [alibaba/EasyRec#176]
Can you please provide an example config on how to output topk (say = 5) items after training the DSSM model? I am unable to find this information in the documentation.

**Comment by poson** [comment]
you need use a vector recall engine， such as faiss。
use  user embedding  to query  item embedding， then get topk items。

**Comment by ss-github-code** [comment]
Thanks for your quick answer, much appreciated @poson! Faiss requires the full set of vectors; can you please let me know how to get this from EasyRec.

**Comment by dawn310826** [comment]
You can use the predict(https://easyrec.readthedocs.io/en/latest/predict/MaxCompute%20%E7%A6%BB%E7%BA%BF%E9%A2%84%E6%B5%8B.html) to get all the vectors.

**Comment by chengmengli06** [comment]
first, you should use this script(https://github.com/alibaba/EasyRec/blob/master/easy_rec/python/tools/split_model_pai.py) to split the model into two parts: user part and item part.

**Comment by ss-github-code** [comment]
Thanks for the help. But I get an error:
  File "/home/shiv/Documents/DataScience/EasyRec/easy_rec/python/tools/split_model_pai.py", line 16, in <module>
    FLAGS = tf.app.flags.FLAGS
AttributeError: module 'tensorflow' has no attribute 'app'

And when I add to force it to use Tensorflow v1 by adding the following two lines:

if tf.__version__ >= '2.0':
  tf = tf.compat.v1

I still don't go too far, please note I am using **dssm_on_taobao.cfg.**

Traceback (most recent call last):
  File "/home/shiv/Documents/DataScience/EasyRec/easy_rec/python/tools/split_model_pai.py", line 271, in <module>
    tf.app.run()
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/shiv/Documents/DataScience/EasyRec/easy_rec/python/tools/split_model_pai.py", line 251, in main
    export(
  File "/home/shiv/Documents/DataScience/EasyRec/easy_rec/python/tools/split_model_pai.py", line 204, in export
    saver = tf_saver.Saver()
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 919, in __init__
    self.build()
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 931, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 959, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 503, in _build_internal
    saveables = saveable_object_util.validate_and_slice_inputs(
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 356, in validate_and_slice_inputs
    for converted_saveable_object in saveable_objects_for_op(op, name):
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 219, in saveable_objects_for_op
    yield ResourceVariableSaveable(variable, "", name)
  File "/home/shiv/anaconda3/envs/RecSys_39/lib/python3.9/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 91, in __init__
    self.handle_op = var.op.inputs[0]
IndexError: tuple index out of range

**Comment by kinghuin** [comment]
Hi, I am also confused by this question. 
Could you please provide documents about [split_model_pai.py](https://github.com/alibaba/EasyRec/blob/master/easy_rec/python/tools/split_model_pai.py) and how to deploy retrieval model with only user tower and faiss?

**Comment by chengmengli06** [comment]
what is your tf version @ss-github-code

**Comment by chengmengli06** [comment]
@kinghuin documentation is in preparation, split_model_pai.py generates two saved_models, one for generating user embedding, and one for generating item embedding. After getting the saved_models, you can do offline prediction( https://easyrec.readthedocs.io/en/latest/predict/MaxCompute%20%E7%A6%BB%E7%BA%BF%E9%A2%84%E6%B5%8B.html) or you can do online prediction by deploying an EAS service[https://easyrec.readthedocs.io/en/latest/predict/%E5%9C%A8%E7%BA%BF%E9%A2%84%E6%B5%8B.html]. Item embeddings are usually predicted offline prediction and then imported to hologres.

**Comment by ss-github-code** [comment]
Sorry for the delay. My tensorflow version is 2.8

**Comment by chengmengli06** [comment]
the script could not work under tf2.x, we are fixing it, the reason is that the variable created in tf2.x are different from tf1.x

**Comment by treper** [comment]
Could you provide a tf2 version script of this split function?
