### ISSUE TITLE
单测文档过时，无法跑通

### ISSUE THREAD

**Issue by GH1995** [alibaba/EasyRec#240]
https://easyrec.readthedocs.io/en/latest/develop.html

```
TEST_DEVICES='' python -m easy_rec.python.test.train_eval_test TrainEvalTest.test_tfrecord_input
```

output
```
Traceback (most recent call last):
  File "/Users/guanhua/opt/miniconda3/envs/easyrec/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/guanhua/opt/miniconda3/envs/easyrec/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/guanhua/work/repo/github/EasyRec/easy_rec/__init__.py", line 18, in <module>
    from easy_rec.python.inference.predictor import Predictor  # isort:skip  # noqa: E402
  File "/Users/guanhua/work/repo/github/EasyRec/easy_rec/python/inference/predictor.py", line 22, in <module>
    from easy_rec.python.protos.dataset_pb2 import DatasetConfig
ModuleNotFoundError: No module named 'easy_rec.python.protos.dataset_pb2'
```

**Comment by yunkchen** [comment]
https://easyrec.readthedocs.io/en/latest/quick_start/local_tutorial.html#easyrec
尝试先按照这个执行一下

**Comment by GH1995** [comment]
> https://easyrec.readthedocs.io/en/latest/quick_start/local_tutorial.html#easyrec 尝试先按照这个执行一下

我使用了 docker ubuntu 18.04 在第一步就无法安装成功

**Comment by yunkchen** [comment]
> > https://easyrec.readthedocs.io/en/latest/quick_start/local_tutorial.html#easyrec 尝试先按照这个执行一下
> 
> 我使用了 docker ubuntu 18.04 在第一步就无法安装成功
这两步骤有执行成功过么：
bash scripts/init.sh
python setup.py install

**Comment by GH1995** [comment]
> > > https://easyrec.readthedocs.io/en/latest/quick_start/local_tutorial.html#easyrec 尝试先按照这个执行一下
> > 
> > 
> > 我使用了 docker ubuntu 18.04 在第一步就无法安装成功
> 
> 这两步骤有执行成功过么： bash scripts/init.sh python setup.py install

执行失败，我用的 docker 链接是 https://hub.docker.com/repository/docker/gh1995/easyrec-dev ，基于 mybigpai-registry.cn-beijing.cr.aliyuncs.com/easyrec/easyrec:py36-tf1.15-0.4.7

**Comment by yunkchen** [comment]
> > > > https://easyrec.readthedocs.io/en/latest/quick_start/local_tutorial.html#easyrec 尝试先按照这个执行一下
> > > 
> > > 
> > > 我使用了 docker ubuntu 18.04 在第一步就无法安装成功
> > 
> > 
> > 这两步骤有执行成功过么： bash scripts/init.sh python setup.py install
> 
> 执行失败

这个报错可以贴一下么？

**Comment by GH1995** [comment]
执行 ` python setup.py install` 时会卡死在这里

```
copying easy_rec.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easy_rec.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
easy_rec.__pycache__.__init__.cpython-38: module references __file__
easy_rec.python.hpo.__pycache__.emr_hpo.cpython-38: module references __file__
easy_rec.python.hpo.__pycache__.pai_hpo.cpython-38: module references __file__
easy_rec.python.hpo_nni.pai_nni.code.__pycache__.utils.cpython-38: module references __file__
easy_rec.python.test.__pycache__.pai_nni_test.cpython-38: module references __file__
creating dist
creating 'dist/easy_rec-0.5.2-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing easy_rec-0.5.2-py3.8.egg
creating /usr/local/lib/python3.8/dist-packages/easy_rec-0.5.2-py3.8.egg
Extracting easy_rec-0.5.2-py3.8.egg to /usr/local/lib/python3.8/dist-packages
Adding easy-rec 0.5.2 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/easy_rec-0.5.2-py3.8.egg
Processing dependencies for easy-rec==0.5.2
Searching for xlrd>=0.9.0
Reading http://mirrors.aliyun.com/pypi/simple/xlrd/
Downloading http://mirrors.aliyun.com/pypi/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl#sha256=6a33ee89877bd9abc1158129f6e94be74e2679636b8a205b43b85206c3f0bbdd
Best match: xlrd 2.0.1
Processing xlrd-2.0.1-py2.py3-none-any.whl
Installing xlrd-2.0.1-py2.py3-none-any.whl to /usr/local/lib/python3.8/dist-packages
Adding xlrd 2.0.1 to easy-install.pth file
Installing runxlrd.py script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/xlrd-2.0.1-py3.8.egg
Searching for tensorflow
Reading http://mirrors.aliyun.com/pypi/simple/tensorflow/
Downloading http://mirrors.aliyun.com/pypi/packages/b0/30/bd03cd1ab1f0b295f37ed96dcee5942f81d4486648adb8079215f5c4f367/tensorflow-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=adc1b80ec32337ba1720fadbf64242aae06a7ee1c7aea6a1a0cffe1968c89b25


```

**Comment by yunkchen** [comment]
> 

可以先环境里装好tf1.15，然后run这个命令
