### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.data' has no attribute 'TableRecordDataset'

### ISSUE THREAD

**Issue by aiot-tech** [alibaba/EasyRec#328]
When running the command to train model: 
```
CUDA_VISIBLE_DEVICES=0 python3 -m easy_rec.python.train_eval --pipeline_config_path deepfm.config
```
Something went wrong
```
AttributeError: module 'tensorflow._api.v2.data' has no attribute 'TableRecordDataset'
```
The operating environment is as follows
```
os: ubuntu16.04
python: 3.8.15
tensorflow-gpu: 2.11.0
easy-rec: 0.6.0(installed from git)
```

**Comment by aiot-tech** [comment]
Details are as follows:
```
Traceback (most recent call last):
  File "/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data3/proj/xh/fs/Torch-RecHub/examples/EasyRec/easy_rec/python/train_eval.py", line 164, in <module>
    _train_and_evaluate_impl(pipeline_config, args.continue_train,
  File "/data3/proj/xh/fs/Torch-RecHub/examples/EasyRec/easy_rec/python/main.py", line 333, in _train_and_evaluate_impl
    estimator_train.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/data3/proj/xh/fs/Torch-RecHub/examples/EasyRec/easy_rec/python/compat/estimator_train.py", line 84, in train_and_evaluate
    result = executor.run()
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/training.py", line 645, in run
    return self.run_local()
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/training.py", line 742, in run_local
    self._estimator.train(
  File "/data3/proj/xh/fs/Torch-RecHub/examples/EasyRec/easy_rec/python/model/easy_rec_estimator.py", line 91, in train
    return super(EasyRecEstimator, self).train(input_fn, hooks, steps,
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 360, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1186, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1212, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1048, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1141, in _call_input_fn
    return input_fn(**kwargs)
  File "/data3/proj/xh/fs/Torch-RecHub/examples/EasyRec/easy_rec/python/input/input.py", line 913, in _input_fn
    dataset = self._build(mode, params)
  File "/data3/proj/xh/fs/Torch-RecHub/examples/EasyRec/easy_rec/python/input/odps_input_v2.py", line 74, in _build
    dataset = tf.data.TableRecordDataset(
AttributeError: module 'tensorflow._api.v2.data' has no attribute 'TableRecordDataset'
```

**Comment by guizili0** [comment]
change your config file: input_type: CSVInput
I think the input_type: OdpsInputV2 did not be supported by public TF.

**Comment by aiot-tech** [comment]
However, there is neither `CSVInput` nor `OdpsInputV2` parameter in the config file copyed from the demo `deepfm`

**Comment by aiot-tech** [comment]
Ok, I run it again with the new fix. Thanks for your reply.
