### ISSUE TITLE
在DeepRec上报错

### ISSUE THREAD

**Issue by supercocoa7654** [alibaba/EasyRec#375]
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from easy_rec.python.model.easy_rec_model import EasyRecModel
[2023-06-03 10:39:27,478][WARNING] pyhive is not installed.
[2023-06-03 10:39:27,544][WARNING] failed to import gen_io_ops.collect_sparse_indices: /home/pai/lib/python3.6/site-packages/easy_rec/python/ops/DeepRec/incr_record.so: undefined symbol: _ZN10tensorflow14DataTypeStringENS_8DataTypeE
[2023-06-03 10:39:27,587][INFO] GraphLearn is not installed. You can install it by "pip install https://easyrec.oss-cn-beijing.aliyuncs.com/3rdparty/graphlearn-0.7-cp27-cp27mu-linux_x86_64.whl"

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

[2023-06-03 10:39:28,329][WARNING] load avx string_split op failed: /home/pai/lib/python3.6/site-packages/easy_rec/python/ops/DeepRec/libstr_avx_op.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
[2023-06-03 10:39:28,352][ERROR] Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/utils/load_class.py", line 142, in import_pkg
    __import__(module_path)
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/input/kafka_dataset.py", line 26, in <module>
    from easy_rec.python.ops import gen_kafka_ops
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/ops/gen_kafka_ops.py", line 26, in <module>
    kafka_module = tf.load_op_library(kafka_ops_path)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/pai/lib/python3.6/site-packages/easy_rec/python/ops/DeepRec/kafka.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/utils/load_class.py", line 142, in import_pkg
    __import__(module_path)
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/input/kafka_dataset.py", line 26, in <module>
    from easy_rec.python.ops import gen_kafka_ops
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/ops/gen_kafka_ops.py", line 26, in <module>
    kafka_module = tf.load_op_library(kafka_ops_path)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/pai/lib/python3.6/site-packages/easy_rec/python/ops/DeepRec/kafka.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pai/lib/python3.6/site-packages/easy_rec/__init__.py", line 38, in <module>
    from easy_rec.python.main import evaluate  # isort:skip  # noqa: E402
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/main.py", line 48, in <module>
    load_class.auto_import()
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/utils/load_class.py", line 185, in auto_import
    import_pkg(pkg_info, prefix_to_remove)
  File "/home/pai/lib/python3.6/site-packages/easy_rec/python/utils/load_class.py", line 146, in import_pkg
    raise ValueError('import module %s failed: %s' % (module_path, str(e)))
ValueError: import module easy_rec.python.input.kafka_dataset failed: /home/pai/lib/python3.6/site-packages/easy_rec/python/ops/DeepRec/kafka.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_
>>>

**Comment by poson** [comment]
如果没有用kafka的话，注释掉kafka_dataset 这个模块
